---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: evelyn-linux
# description will be included in the image's metadata
description: Linux distro based on Aurora for my gf.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  
  - type: rpm-ostree
    install:
      - btop
      - tlp
      - tlp-rdw
      
  - type: default-flatpaks
    configurations:
    - name: standard
      flatpaks:
        - app.eduroam.geteduroam
        - app.zen_browser.zen
        - com.github.tchx84.Flatseal
        - com.ranfdev.DistroShelf
        - com.rtosta.zapzap
        - io.github.brunofin.Cohesion
        - io.github.cosmic_utils.camera
        - io.github.flattool.Warehouse
        - io.github.kolunmi.Bazaar
        - io.missioncenter.MissionCenter
        - it.mijorus.gearlever
        - org.audacityteam.Audacity
        - org.deskflow.deskflow
        - org.fedoraproject.MediaWriter
        - org.fkoehler.KTailctl
        - org.gnome.Calendar
        - org.gnome.DejaDup
        - org.kde.gwenview
        - org.kde.haruna
        - org.kde.kcalc
        - org.kde.kclock
        - org.kde.kdenlive
        - org.kde.kontact
        - org.kde.kweather
        - org.kde.marknote
        - org.kde.okular
        - org.kde.skanpage
        - org.mozilla.Thunderbird
        - org.onlyoffice.desktopeditors
        - org.telegram.desktop
        - org.videolan.VLC
