name: bluebuild
on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here
          - recipe.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: true
          build_opts: --no-sign
  generate-iso:
    name: Generate ISO
    runs-on: ubuntu-latest
    needs: bluebuild  # Aspetta che la build dell'immagine sia completa
    permissions:
      contents: read
      packages: read
    steps:
      - name: Install BlueBuild CLI
        run: |
          sudo docker create --name blue-build-installer ghcr.io/blue-build/cli:v0.9-installer
          sudo docker cp blue-build-installer:/out/bluebuild /usr/bin/bluebuild
          sudo docker rm blue-build-installer

      - name: Generate ISO
        run: bluebuild generate-iso --iso-name EvelynLinux.iso image ghcr.io/tianotsenpai/evelyn-linux:latest

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: EvelynLinux-ISO
          path: EvelynLinux.iso
          retention-days: 7  # conserva l'ISO per 7 giorni
